<#
.SYNOPSIS
    Regenerates constraints.txt, the full pinned dependency set for Linux.

.DESCRIPTION
    Direct dependencies are pinned in pyproject.toml. This script resolves them
    (including the dev extra) inside the same base image the service runs on
    and freezes the result, so Docker builds and CI install identical versions.

    Run it after changing any dependency in pyproject.toml and commit the result.
#>
[CmdletBinding()]
param(
    [string]$Image = 'python:3.12-slim'
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

$script = @'
set -e
cp -r /src /tmp/build
cd /tmp/build
pip install --quiet --disable-pip-version-check --root-user-action=ignore ".[dev]"
pip freeze --exclude parcelpulse-api --exclude-editable
'@ -replace "`r", ''

$frozen = docker run --rm -v "${repoRoot}:/src:ro" $Image sh -c $script
if ($LASTEXITCODE -ne 0) {
    throw "Dependency resolution failed (docker exit code $LASTEXITCODE)."
}

$header = @(
    '# Full pinned dependency set for Linux (python:3.12-slim).'
    '# Generated by scripts/update-constraints.ps1 - do not edit by hand.'
)
$content = ($header + $frozen) -join "`n"
[System.IO.File]::WriteAllText((Join-Path $repoRoot 'constraints.txt'), $content + "`n")
Write-Host "Wrote constraints.txt ($($frozen.Count) packages)."
